# Generated by Django 6.0.7 on 2026-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="goal",
            name="progress",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("일반", "일반"),
                    ("휴가", "휴가"),
                    ("외박", "외박"),
                    ("외출", "외출"),
                ],
                default="일반",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("행복", "😊"),
                    ("보통", "😐"),
                    ("지침", "😔"),
                    ("운동", "💪"),
                    ("학습", "📚"),
                    ("졸림", "😴"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
