# Generated by Django 6.0.7 on 2026-08-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0003_alter_journalentry_unique_together_serviceinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceInfo",
        ),
    ]
