# Generated by Django 6.0.7 on 2026-07-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                choices=[("병사", "병사"), ("간부", "간부")],
                default="병사",
                max_length=10,
            ),
        ),
    ]
