# Generated by Django 6.0.7 on 2026-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
