# Generated by Django 6.0.7 on 2026-07-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_rename_conversation_message_conversation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="Conversation",
            new_name="conversation",
        ),
    ]
